# Generated by Django 5.0.4 on 2024-04-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_artist_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
