# Generated by Django 5.0.4 on 2024-04-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_feature_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file',
        ),
    ]
