# Generated by Django 5.0.4 on 2024-04-10 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='music.album'),
        ),
    ]
